apiVersion: v1
kind: Pod
metadata:
  name: probe
spec:
  containers:
  - image: nginx
    name: nginx
    livelinessprobe:
      httpGet:
        path: /
        port: 80
      InitialDelaySeconds: 3
      PeriodSeconds: 5